import {useEffect,useMemo,useRef,useState} from 'react';
import Scene,{Plane,type View} from './Scene.js';
import {DEFAULT,MODEL,MATERIALS,PRESETS,validate,compile,properties,resize,EARTH,type Design,type Result} from '../simulation/engine.js';
import {elapsed,sample} from './view.js';
import './lab.css';
function Icon({kind}:{kind:string}){return <span aria-hidden="true" className={`ui-icon ${kind}`}>{kind==='play'?'▶':kind==='pause'?'Ⅱ':kind==='reset'?'↺':kind==='share'?'↗':kind==='step'?'▸':'·'}</span>;}
function Field({label,unit,value,min,max,step,onChange}:{label:string;unit:string;value:number;min:number;max:number;step:number;onChange:(n:number)=>void}){
 return <label className="field"><span className="field-top"><span>{label}</span><span className="number-input"><input aria-label={`${label} value`} type="number" value={value} min={min} max={max} step={step} onChange={e=>onChange(Number(e.target.value))}/><span>{unit}</span></span></span><input aria-label={label} type="range" min={min} max={max} step={step} value={value} onChange={e=>onChange(Number(e.target.value))}/></label>;
}
export default function Lab(){
 const [design,setDesign]=useState<Design>({...DEFAULT}),[result,setResult]=useState<Result|null>(null),[busy,setBusy]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [time,setTime]=useState(0),[playing,setPlaying]=useState(false),[speed,setSpeed]=useState(240),[view,setView]=useState<View>('earth'),[gpu,setGpu]=useState(true),[tab,setTab]=useState('fly'),[shareUrl,setShareUrl]=useState(''),[previous,setPrevious]=useState<Result|null>(null);
 const clock=useRef(0),worker=useRef<Worker|null>(null),request=useRef(0),input=useRef<HTMLInputElement>(null),playingRef=useRef(playing),speedRef=useRef(speed),resultRef=useRef(result);
 playingRef.current=playing;speedRef.current=speed;resultRef.current=result;
 const max=result?.frames.at(-1)?.t??0,dirty=!!result&&JSON.stringify(design)!==JSON.stringify(result.design);
 const frame=useMemo(()=>result?sample(result,time):null,[result,time]);
 const currentEvent=result?.events.filter(e=>e.t<=time+0.01).at(-1);
 const material=MATERIALS.find(m=>m.id===design.material)!;
 const draftInfo=useMemo(()=>{try{const d=validate(design);return {body:compile(d,0,false),props:properties(d)};}catch{return null;}},[design]);
 const run=(d:Design,autoPlay=true)=>{
  try{validate(d);}catch(e){setError((e as Error).message);setBusy(false);return;}
  worker.current?.terminate();setBusy(true);setPlaying(false);setError('');setNotice('');const id=++request.current;
  const w=new Worker(new URL('./worker.ts',import.meta.url),{type:'module'});worker.current=w;
  w.onerror=()=>{if(id===request.current){setError('The calculation worker could not start. Reload the lab or use a supported browser.');setBusy(false);}w.terminate();};
  w.onmessage=e=>{if(e.data.id!==request.current)return;setBusy(false);w.terminate();worker.current=null;
   if(e.data.error){setError(e.data.error);return;}
   if(resultRef.current)setPrevious(resultRef.current);setResult(e.data.result);clock.current=0;setTime(0);setPlaying(autoPlay&&!window.matchMedia('(prefers-reduced-motion: reduce)').matches);
  };w.postMessage({id,design:d});
 };
 useEffect(()=>{let initial={...DEFAULT},shareError='';try{const raw=new URLSearchParams(location.hash.slice(1)).get('d');if(raw){if(raw.length>6000)throw Error('Shared design exceeds the size limit.');initial=validate(JSON.parse(raw));}}catch(e){shareError=`Shared design not loaded: ${(e as Error).message}`;}
  setDesign(initial);run(initial,false);if(shareError)setNotice(shareError);return()=>worker.current?.terminate();
 },[]);
 useEffect(()=>{let raf=0,last=performance.now(),lastUI=0;
 const tick=(now:number)=>{raf=requestAnimationFrame(tick);const dt=Math.min(.1,(now-last)/1000);last=now;if(!playingRef.current||document.hidden||!resultRef.current)return;const end=resultRef.current.frames.at(-1)?.t??0;clock.current=Math.min(end,clock.current+dt*speedRef.current);if(now-lastUI>80||clock.current===end){setTime(clock.current);lastUI=now;}if(clock.current===end)setPlaying(false);};raf=requestAnimationFrame(tick);return()=>cancelAnimationFrame(raf);},[]);
 const seek=(t:number)=>{setPlaying(false);clock.current=Math.max(0,Math.min(max,t));setTime(clock.current);};
 const change=<K extends keyof Design>(k:K,v:Design[K])=>{setDesign(d=>({...d,[k]:v}));setPlaying(false);setError('');};
 const share=async()=>{try{const d=validate(design),url=`${location.origin}${location.pathname}#d=${encodeURIComponent(JSON.stringify(d))}`;history.replaceState(null,'',url);setShareUrl(url);try{await navigator.clipboard.writeText(url);setNotice('Design link copied. It includes this model version and all editable inputs.');}catch{setNotice('Copy the design link below.');}}catch(e){setError((e as Error).message);}};
 const save=()=>{try{localStorage.setItem('skyhook-lab-design-v1',JSON.stringify(validate(design)));setNotice('Design saved on this browser. Export JSON for a portable copy.');}catch(e){setError(`Could not save: ${(e as Error).message}`);}};
 const load=()=>{try{const d=validate(JSON.parse(localStorage.getItem('skyhook-lab-design-v1')??'null'));setDesign(d);run(d,false);}catch(e){setError(`Could not load a saved design: ${(e as Error).message}`);}};
 const download=()=>{try{const d=validate(design),url=URL.createObjectURL(new Blob([JSON.stringify(d,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='skyhook-tether-design.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setError((e as Error).message);}};
 const importFile=async(file?:File)=>{if(!file)return;try{if(file.size>16000)throw Error('Design file exceeds 16 KB.');const d=validate(JSON.parse(await file.text()));setDesign(d);run(d,false);}catch(e){setError(`Import rejected: ${(e as Error).message}`);}finally{if(input.current)input.current.value='';}};
 const eventStep=(dir:number)=>{if(!result)return;const list=result.events.filter(e=>dir>0?e.t>time+0.1:e.t<time-0.1);seek((dir>0?list[0]:list.at(-1))?.t??(dir>0?max:0));};
 const error3D=(msg:string)=>{setGpu(false);setView('plane');setNotice(msg);};
 return <div className={`tether-lab tab-${tab}`}>
  <header className="lab-header"><a className="lab-brand" href="/" aria-label="Skyhook Industries home"><span className="brand-orbit" aria-hidden="true"/><span>SKYHOOK <span className="brand-divider">/</span> <b>TETHER LAB</b></span></a><nav aria-label="Lab navigation"><a href="/research/">Research</a><a href="/lab/method/">How it works</a><button className="share-button" onClick={share}>Share design <Icon kind="share"/></button></nav></header>
  <div className="lab-intro"><div><div className="intro-kicker">THE ORBITAL WORKSHOP <span>First playable · Earth</span></div><h1>Make the second delivery.</h1><p>A payload leaves with more energy. Your tether has to earn it back.</p></div><div className="model-status"><span className="status-square"/> D1p / rigid-body model<a href="/lab/method/#scope">Assumptions & limits ↗</a></div></div>
  <nav className="mobile-tabs" aria-label="Workspace panels">{['build','fly','results','learn'].map(t=><button key={t} aria-pressed={tab===t} onClick={()=>setTab(t)}>{t}</button>)}</nav>
  {error&&<div className="feedback error" role="alert">{error}<button onClick={()=>setError('')} aria-label="Dismiss error">×</button></div>}
  {notice&&<div className="feedback" role="status">{notice}<button onClick={()=>setNotice('')} aria-label="Dismiss notification">×</button></div>}
  {shareUrl&&<div className="share-output"><label>Design link <input aria-label="Shareable design link" readOnly value={shareUrl} onFocus={e=>e.target.select()}/></label><button onClick={()=>setShareUrl('')} aria-label="Close share link">×</button></div>}
  <div className="lab-workspace">
   <aside className="build-panel" aria-label="Design controls"><div className="panel-title"><h2>Build your tether</h2><span>01 / CONFIGURE</span></div>
    <label className="select-label">Start from an experiment<select aria-label="Experiment preset" value="" onChange={e=>{const p=PRESETS.find(p=>p.id===e.target.value);if(p){setDesign({...p.design});run(p.design,false);setTab('fly');}}}><option value="" disabled>Choose a preset…</option>{PRESETS.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>
    <div className="control-group"><h3>Structure</h3><div className="segmented"><button aria-pressed={design.shape==='uniform'} onClick={()=>change('shape','uniform')}>Uniform</button><button aria-pressed={design.shape==='tapered'} onClick={()=>change('shape','tapered')}>Tapered</button></div>
    <label className="select-label">Load-bearing material<select aria-label="Tether material" value={design.material} onChange={e=>change('material',e.target.value)}>{MATERIALS.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label>
    <div className="material-readout"><strong>{draftInfo?(draftInfo.props.allowable/1e9).toFixed(2):'—'} <span>GPa assumed allowable</span></strong><p>{material.id==='future'||material.id==='custom'?'Hypothetical properties. Explore, don’t mistake this for available hardware.':'Published fiber data, divided by the selected safety factor. Environmental losses are not modeled.'}</p></div>
    {design.material==='custom'&&<><Field label="Material density" unit="kg/m³" value={design.density} min={500} max={12000} step={50} onChange={v=>change('density',v)}/><Field label="Ultimate stress" unit="GPa" value={design.ultimateGPa} min={.1} max={100} step={.1} onChange={v=>change('ultimateGPa',v)}/></>}
    <Field label="Total tether span" unit="km" value={design.spanKm} min={80} max={4000} step={20} onChange={v=>change('spanKm',v)}/>
    <Field label="Center cross-section" unit="mm²" value={design.areaMm2} min={5} max={2500} step={1} onChange={v=>change('areaMm2',v)}/>
    <button className="resize-button" onClick={()=>{try{const area=resize(validate(design));change('areaMm2',area);setNotice(`Center cross-section set to ${area} mm². Sized for the lower-radial load with a 15% area reserve, not certified for the complete mission. Run to check the trajectory.`);}catch(e){setError((e as Error).message);}}}>Resize for radial load <span>↗</span></button></div>
    <div className="control-group"><h3>Orbit & payload</h3><Field label="Initial circular altitude" unit="km" value={design.altitudeKm} min={400} max={8000} step={50} onChange={v=>change('altitudeKm',v)}/><Field label="Initial tip speed vs. center" unit="km/s" value={design.tipSpeedKms} min={.25} max={2.5} step={.05} onChange={v=>change('tipSpeedKms',v)}/><Field label="Payload per delivery" unit="t" value={design.payloadT} min={.1} max={20} step={.1} onChange={v=>change('payloadT',v)}/><Field label="Earth-relative release phase" unit="°" value={design.releaseDeg} min={70} max={210} step={5} onChange={v=>change('releaseDeg',v)}/></div>
    <div className="control-group"><h3>Recovery</h3><div className="segmented"><button aria-pressed={design.recovery==='chemical'} onClick={()=>change('recovery','chemical')}>Chemical</button><button aria-pressed={design.recovery==='none'} onClick={()=>change('recovery','none')}>Coast</button></div><Field label="Propellant budget" unit="t" value={design.fuelT} min={0} max={80} step={1} onChange={v=>change('fuelT',v)}/><p className="control-note">Electrodynamic and traffic-exchange recovery are planned, not simulated in this build.</p></div>
    <details className="expert"><summary>More engineering controls</summary><Field label="Safety factor" unit="×" value={design.safetyFactor} min={1.2} max={5} step={.1} onChange={v=>change('safetyFactor',v)}/><Field label="Total available thrust" unit="N" value={design.thrustN} min={100} max={10000} step={100} onChange={v=>change('thrustN',v)}/><Field label="Specific impulse" unit="s" value={design.isp} min={150} max={450} step={5} onChange={v=>change('isp',v)}/><p className="control-note">Hub: 30 t. Terminal modules: 2 t each. A tapered profile ends at 30% of its center area. Fuel is carried at the hub.</p></details>
    <div className="design-actions"><button onClick={save}>Save locally</button><button onClick={load}>Load</button><button onClick={download}>Export JSON</button><button onClick={()=>input.current?.click()}>Import</button><input ref={input} type="file" hidden accept=".json,application/json" onChange={e=>importFile(e.target.files?.[0])}/></div>
   </aside>
   <section className="flight-panel" aria-label="Flight workspace"><div className="scene-toolbar"><div className="view-switch" role="group" aria-label="View mode"><button disabled={!gpu} aria-pressed={view==='earth'} onClick={()=>setView('earth')}>Earth</button><button aria-pressed={view==='plane'} onClick={()=>setView('plane')}>Orbital plane</button><button disabled={!gpu} aria-pressed={view==='follow'} onClick={()=>setView('follow')}>Follow tether</button></div><span className="scene-coordinate">EARTH-CENTERED · SI CORE</span></div>
    <div className="scene-box">{result?(view==='plane'?<Plane result={result} clock={clock}/>:<Scene result={result} clock={clock} view={view} onFailure={error3D}/>):<div className="scene-loading"><div className="loading-orbit"/><p>{busy?'Computing the opening experiment…':'No valid trajectory yet.'}</p></div>}
     {busy&&result&&<div className="scene-pending">Computing new mission… <button onClick={()=>{worker.current?.terminate();worker.current=null;request.current++;setBusy(false);}}>Cancel</button></div>}
     {dirty&&!busy&&<div className="stale-notice">Design changed · showing the previous run</div>}
     <div className="scene-legend"><span><i className="legend-line"/> Facility</span><span><i className="legend-line payload"/> Released payload</span><span><i className="legend-line dashed"/> Initial orbit</span></div>
    </div>
    <div className="scene-caption"><span>Drag to orbit · scroll to zoom</span><span>Markers and cable width enlarged for visibility</span></div>
    <div className="timeline"><div className="transport"><button className="run-button" onClick={()=>{if(busy)return;if(dirty||!result)run(design);else if(time>=max){seek(0);setPlaying(true);}else setPlaying(!playing);}} disabled={busy}>{busy?'Calculating…':dirty?'Run changed design':playing?<><Icon kind="pause"/> Pause</>:<><Icon kind="play"/> {time===0?'Fly mission':'Play'}</>}</button><button className="transport-small" onClick={()=>seek(0)} disabled={!result} aria-label="Restart replay"><Icon kind="reset"/></button><button className="transport-small" onClick={()=>eventStep(1)} disabled={!result} aria-label="Next mission event"><Icon kind="step"/></button><span className="mission-clock">T+ {elapsed(time)}</span><label className="speed-label">Speed<select aria-label="Playback speed" value={speed} onChange={e=>setSpeed(Number(e.target.value))}><option value={60}>60×</option><option value={240}>240×</option><option value={600}>600×</option></select></label></div>
    <input className="timeline-scrub" aria-label="Mission time" type="range" min={0} max={max||1} step={1} value={time} disabled={!result} onChange={e=>seek(Number(e.target.value))}/><div className="timeline-events">{result?.events.filter(e=>['capture','release','ready','end','limit'].includes(e.kind)).map((e,i)=><button key={i} className={e.t<=time+.01?'visited':''} onClick={()=>seek(e.t)}><span>{elapsed(e.t)}</span>{e.title.replace('Payload ','').replace(' captured',' · capture').replace(' released',' · release')}</button>)}</div></div>
    <div className="mission-narration" aria-live="polite"><span className="narration-index">FLIGHT LOG</span><div><h2>{currentEvent?.title??'Your first orbital experiment'}</h2><p>{currentEvent?.detail??'Change a material, fly the mission, and inspect what the payload gains and the facility gives up.'}</p></div></div>
   </section>
   <aside className="results-panel" aria-label="Mission telemetry"><div className="panel-title"><h2>Mission telemetry</h2><span>{dirty?'PREVIOUS RUN':'CALCULATED'}</span></div><div className="delivery-count"><span>DELIVERIES</span><strong>{frame?.deliveries??0}<small>/ 2</small></strong><p>Higher-energy orbit, then repeat.</p></div>
    <dl className="telemetry"><div><dt>Facility altitude</dt><dd>{frame?((Math.hypot(frame.state[0],frame.state[1])-EARTH)/1000).toFixed(0):'—'}<span>km</span></dd></div><div><dt>Closest tether point</dt><dd>{frame?(frame.clearance/1000).toFixed(0):'—'}<span>km</span></dd></div><div><dt>Axial load margin</dt><dd className={frame&&frame.margin<1?'bad':''}>{frame?Math.min(99,frame.margin).toFixed(2):'—'}<span>×</span></dd></div><div><dt>Propellant remaining</dt><dd>{frame?(frame.fuel/1000).toFixed(2):'—'}<span>t</span></dd></div></dl>
    <div className="mass-card"><span>THIS DESIGN · DRY MASS</span><strong>{draftInfo?(draftInfo.body.mass/1000).toFixed(1):'—'}<small> t</small></strong><p>{draftInfo?(draftInfo.body.structural/1000).toFixed(1):'—'} t tether + 34 t hub and terminals. No payload or propellant.</p></div>
    {result&&time>=max-.1&&<div className={`outcome ${result.outcome==='complete'?'success':''}`} role="status"><h3>{result.outcome==='complete'?'Second delivery achieved':result.outcome==='limit'?'A useful limit':'There’s another trade to make'}</h3><p>{result.reason}</p><p><strong>{(result.fuelUsed/1000).toFixed(2)} t</strong> propellant used. This guidance is not fuel-optimal.</p>{result.deliveries.map(d=><p key={d.number}>Payload {d.number}: <strong>+{(d.gain/1e6).toFixed(1)} MJ/kg</strong></p>)}</div>}
    {previous&&result&&<details className="comparison"><summary>Compare with previous run</summary><p>Previous: {previous.deliveries.length} deliveries, {(previous.fuelUsed/1000).toFixed(2)} t fuel.</p><p>Current: {result.deliveries.length} deliveries, {(result.fuelUsed/1000).toFixed(2)} t fuel.</p><p>Each result retains its own inputs. These are not normalized rankings.</p></details>}
    <div className="try-next"><h3>Try one change.</h3><p>Switch recovery to <b>Coast</b>. The first delivery still works. Watch what happens to the second.</p><button onClick={()=>{const d={...design,recovery:'none' as const};setDesign(d);run(d);}}>Try without reboost →</button></div>
   </aside>
  </div>
  <section className="learn-panel"><div><span className="intro-kicker">A SMALL LAB, AN EXPLICIT MODEL</span><h2>The animation follows the physics.</h2><p>Distributed gravity turns the tether. Capture changes its center of mass. Release gives the payload its actual velocity. Chemical recovery spends finite propellant; nothing resets the orbit behind the scenes.</p></div><div><h3>What this build does not claim</h3><p>This is a planar rigid-body experiment with axial-load screening. It does not model cable waves, atmospheric capture, damage, electrodynamics, inbound traffic recovery or the solar system. A successful run is not a flight-qualified design.</p><a href="/lab/method/">Read the equations, sources and tests ↗</a></div></section>
  <footer className="lab-footer"><span>SKYHOOK INDUSTRIES · TETHER LAB</span><span>{MODEL} · local browser simulation</span><a href="https://github.com/RelyOnFire/skyhook-industries">Inspect the source ↗</a></footer>
 </div>;
}
