import {useEffect,useMemo,useRef,useState,useCallback} from 'react';
import {DEFAULT,EDT_PRESET,MATERIALS,type Design} from '../../simulation/engine.js';
import {OPS_MODEL,OPS_DEFAULT,OPS_PRESETS,validateOps,readOps,opsFragment,makeManifest,unpoweredCopy,sampleOps,type OpsPlan,type OpsResult} from '../../simulation/operations.js';
import {elapsed} from '../view.js';
import OperationsScene from './Scene.js';
import './operations.css';
const f=(n:number,d=1)=>Number.isFinite(n)?n.toLocaleString('en-US',{maximumFractionDigits:d}):'—';
const plus=(n:number,d=2)=>(n>0?'+':'')+f(n,d);
const copy=(p:OpsPlan):OpsPlan=>JSON.parse(JSON.stringify(p));
const store='skyhook-operations-v1';
function NumberField({label,value,min,max,step=1,unit='',change}:{label:string;value:number;min:number;max:number;step?:number;unit?:string;change:(n:number)=>void}){
  return <label className="ops-field"><span>{label}<small>{unit}</small></span><input aria-label={label} type="number" min={min} max={max} step={step} value={Number.isFinite(value)?value:''} aria-invalid={!Number.isFinite(value)||value<min||value>max||undefined} onChange={e=>change(e.currentTarget.value===''?NaN:Number(e.currentTarget.value))}/></label>;
}
function History({r,time,metric}:{r:OpsResult;time:number;metric:'energy'|'angular'}){
  const unit=metric==='energy'?'GJ':'10¹² kg·m²/s',get=(i:number)=>metric==='energy'?(r.frames[i].dryEnergyJ-r.initialDryEnergyJ)/1e9:(r.frames[i].dryAngular-r.initialDryAngular)/1e12;
  const vals=r.frames.map((_,i)=>get(i)),lo=Math.min(0,...vals),hi=Math.max(0,...vals),span=Math.max(1e-5,hi-lo),end=r.frames.at(-1)!.t||1;
  const points=r.frames.map((p,i)=>`${55+p.t/end*565},${160-(get(i)-lo)/span*130}`).join(' ');
  return <div className="ops-history"><div><h3>{metric==='energy'?'Energy held by the dry facility':'Angular momentum of the dry facility'}</h3><span>{unit} · change from start</span></div><svg viewBox="0 0 660 200" role="img" aria-label={`${metric} history of the same dry facility; excludes propellant and attached cargo`}>
    {[0,.5,1].map(u=><g key={u}><line x1="55" x2="620" y1={160-u*130} y2={160-u*130} className="ops-grid"/><text x="48" y={164-u*130} textAnchor="end">{f(lo+span*u,2)}</text></g>)}
    <polyline points={points} fill="none" className="ops-history-line"/>
    <line x1={55+time/end*565} x2={55+time/end*565} y1="20" y2="163" className="ops-cursor"/>
    {[0,.25,.5,.75,1].map(u=><text key={u} x={55+565*u} y="184" textAnchor="middle">{f(u*end/3600,1)} h</text>)}
  </svg><p>The same dry structure throughout; excludes fuel and attached cargo. Not a sustainability certificate. Exact event and resource accounting is below.</p></div>;
}
export default function Operations(){
  const [plan,setPlan]=useState<OpsPlan>(()=>copy(OPS_DEFAULT)),[result,setResult]=useState<OpsResult|null>(null),[baseline,setBaseline]=useState<OpsResult|null>(null);
  const [busy,setBusy]=useState(false),[progress,setProgress]=useState(0),[error,setError]=useState(''),[notice,setNotice]=useState(''),[share,setShare]=useState('');
  const [panel,setPanel]=useState<'plan'|'flight'|'results'>('flight'),[time,setTime]=useState(0),[playing,setPlaying]=useState(false),[speed,setSpeed]=useState(600),[plane,setPlane]=useState(false),[follow,setFollow]=useState(false),[selected,setSelected]=useState('facility');
  const [out,setOut]=useState(6),[incoming,setIncoming]=useState(0),[mass,setMass]=useState(3),[interval,setInterval]=useState(90);
  const worker=useRef<Worker|null>(null),sequence=useRef(0),file=useRef<HTMLInputElement>(null),fuelMemory=useRef(40);
  const clock=useRef(0),view=useRef({playing,speed,result});view.current={playing,speed,result};
  const validation=useMemo(()=>{try{return {plan:validateOps(plan),error:''};}catch(e){return {plan:null,error:(e as Error).message};}},[plan]);
  const dirty=!!result&&(!!validation.error||JSON.stringify(validation.plan)!==JSON.stringify(validateOps(result.plan)));
  const frame=useMemo(()=>result?sampleOps(result,time):null,[result,time]);
  const lastEvent=result?.events.filter(e=>e.t<=time+.01).at(-1),end=result?.frames.at(-1)?.t??0;
  const update=(edit:Partial<OpsPlan>)=>{setPlan(p=>({...p,...edit}));setPlaying(false);setError('');};
  const changeDesign=(edit:Partial<Design>)=>{setPlan(p=>({...p,design:{...p.design,...edit}}));setPlaying(false);setError('');};
  const run=(p:OpsPlan)=>{
    try{const clean=validateOps(p);worker.current?.terminate();const id=++sequence.current;setBusy(true);setProgress(0);setPlaying(false);setError('');setNotice('');
      const w=new Worker(new URL('./worker.ts',import.meta.url),{type:'module'});worker.current=w;
      w.onmessage=e=>{if(e.data.id!==sequence.current)return;if(e.data.fraction!==undefined){setProgress(e.data.fraction);return;}setBusy(false);w.terminate();worker.current=null;if(e.data.error){setError(e.data.error);return;}setResult(e.data.result);setSelected(old=>old==='facility'||e.data.result.rows.some((r:{id:string})=>r.id===old)?old:'facility');setTime(0);clock.current=0;setPanel('flight');};
      w.onerror=()=>{if(id===sequence.current){setBusy(false);setError('The operations worker failed. Your previous run is preserved.');}w.terminate();};w.postMessage({id,plan:clean});
    }catch(e){setError((e as Error).message);}
  };
  const adopt=(p:OpsPlan)=>{setPlan(copy(p));if(p.design.recovery==='chemical')fuelMemory.current=p.design.fuelT;setSelected('facility');run(p);};
  useEffect(()=>{let initial=copy(OPS_DEFAULT),message='';try{const raw=new URLSearchParams(location.hash.slice(1)).get('ops');if(raw)initial=readOps(raw);}catch(e){message=`Shared plan not loaded: ${(e as Error).message}`;}setPlan(initial);if(initial.design.recovery==='chemical')fuelMemory.current=initial.design.fuelT;run(initial);if(message)setNotice(message);return()=>{sequence.current++;worker.current?.terminate();};},[]);
  useEffect(()=>{let raf=0,last=performance.now(),ui=0;const tick=(now:number)=>{raf=requestAnimationFrame(tick);const dt=Math.min(.1,(now-last)/1000);last=now;const v=view.current;if(!v.playing||document.hidden||!v.result)return;const end=v.result.frames.at(-1)!.t;clock.current=Math.min(end,clock.current+dt*v.speed);if(now-ui>100||clock.current===end){setTime(clock.current);ui=now;}if(clock.current===end)setPlaying(false);};raf=requestAnimationFrame(tick);return()=>cancelAnimationFrame(raf);},[]);
  const seek=(t:number)=>{setPlaying(false);clock.current=Math.max(0,Math.min(end,t));setTime(clock.current);};
  const fallback=useCallback(()=>{setPlane(true);setNotice('WebGL is unavailable. The orbital-plane view uses the same calculated states.');},[]);
  const save=()=>{try{localStorage.setItem(store,JSON.stringify(validateOps(plan)));setNotice('Operations plan saved in this browser.');}catch(e){setError((e as Error).message);}};
  const load=()=>{try{const raw=localStorage.getItem(store);if(!raw)throw Error('No saved operations plan.');adopt(readOps(raw));}catch(e){setError((e as Error).message);}};
  const exportData=(data:unknown,name:string)=>{const u=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);};
  const sharing=async()=>{try{const url=`${location.origin}${location.pathname}${opsFragment(plan)}`;history.replaceState(null,'',url);setShare(url);try{await navigator.clipboard.writeText(url);setNotice('Operations link copied.');}catch{setNotice('Copy the operations link below.');}}catch(e){setError((e as Error).message);}};
  const counts=result?{out:result.plan.manifest.filter(r=>r.direction==='outbound').length,in:result.plan.manifest.filter(r=>r.direction==='inbound').length}:null;
  const final=result?.frames.at(-1),gain=result?result.rows.reduce((s,r)=>s+(r.energyGainJ??0),0):0;
  return <main id="lab-content" className="ops-app">
    <header className="ops-header"><div><p className="micro">OPERATIONS / EARTH ORBIT</p><h1>Keep the next flight possible.</h1><p>A finite manifest. One evolving machine. Nothing resets between shipments.</p></div><div className="ops-top-actions"><button disabled={!validation.plan} onClick={save}>Save plan</button><button onClick={load}>Load</button><button disabled={!validation.plan} onClick={sharing}>Share shift ↗</button></div></header>
    {busy&&<section className="ops-computing" aria-label="Operations calculation"><span>Calculating a continuous shift · {Math.round(progress*100)}%</span><progress max={1} value={progress} aria-label="Operations calculation progress"/><button onClick={()=>{worker.current?.terminate();sequence.current++;setBusy(false);setNotice('Calculation cancelled. The previous shift is intact.');}}>Cancel operations</button></section>}
    <section className="ops-presets" aria-label="Operations presets">{OPS_PRESETS.map(p=><button key={p.id} disabled={busy} onClick={()=>adopt(p.plan)}><b>{p.title}</b><span>{p.detail}</span><i aria-hidden="true">↗</i></button>)}</section>
    {(error||notice)&&<div className={`ops-feedback ${error?'error':''}`} role={error?'alert':'status'}><span>{error||notice}</span><button aria-label="Dismiss operations message" onClick={()=>{setError('');setNotice('');}}>×</button></div>}
    {share&&<label className="ops-share">Shareable shift<input aria-label="Shareable operations link" readOnly value={share} onFocus={e=>e.currentTarget.select()}/><button onClick={()=>setShare('')}>Close</button></label>}
    <nav className="ops-tabs" aria-label="Operations panels">{(['plan','flight','results'] as const).map(tab=><button key={tab} aria-pressed={panel===tab} onClick={()=>{setPanel(tab);if(window.innerWidth>800)document.querySelector(tab==='plan'?'.ops-planning':tab==='flight'?'.ops-flight':'.ops-results')?.scrollIntoView({block:'start'});}}>{tab==='plan'?'Manifest & design':tab==='flight'?'Live shift':'Results & balance'}</button>)}</nav>
    <div className={`ops-workspace ops-panel-${panel}`}>
      <aside className="ops-planning" aria-label="Operations planning">
        <div className="ops-section-title"><span className="micro">DISPATCH RULES</span><span className="ops-badge">{dirty?'UNRUN EDITS':OPS_MODEL}</span></div>
        <label className="ops-select">Experiment<select aria-label="Operations mode" value={plan.mode} onChange={e=>update({mode:e.target.value as OpsPlan['mode']})}><option value="capacity">Capacity: dispatch when ready</option><option value="schedule">Schedule: fixed capture windows</option></select></label>
        <p className="ops-note">{plan.mode==='capacity'?'The queue order is fixed; window times are ignored. This measures available service, not punctuality.':'The entered windows stay fixed. A shipment that misses its window is not moved to a more convenient time.'}</p>
        <div className="ops-two"><NumberField label="Observation horizon" value={plan.horizonHours} min={.25} max={24} step={.25} unit="h" change={v=>update({horizonHours:v})}/>{plan.mode==='schedule'&&<NumberField label="Capture window half-width" value={plan.windowMinutes} min={.5} max={30} step={.5} unit="min" change={v=>update({windowMinutes:v})}/>}</div>
        <label className="ops-select">Powered recovery<select aria-label="Operations recovery" value={plan.design.recovery} onChange={e=>{if(plan.design.recovery==='chemical')fuelMemory.current=plan.design.fuelT;changeDesign({recovery:e.target.value as Design['recovery'],fuelT:e.target.value==='chemical'?fuelMemory.current:0});}}><option value="none">None / traffic only</option><option value="chemical">Chemical assistance</option><option value="electrodynamic">Electrodynamic E0 assistance</option></select></label>
        {plan.design.recovery==='chemical'&&<div className="ops-two"><NumberField label="Shift propellant" value={plan.design.fuelT} min={0} max={80} unit="t" change={v=>changeDesign({fuelT:v})}/><NumberField label="Available thrust" value={plan.design.thrustN} min={100} max={10000} step={100} unit="N" change={v=>changeDesign({thrustN:v})}/></div>}
        {plan.design.recovery==='electrodynamic'&&<><div className="ops-two"><NumberField label="Bus power cap" value={plan.design.edPowerKw} min={0} max={5000} step={25} unit="kW" change={v=>changeDesign({edPowerKw:v})}/><NumberField label="Circuit current cap" value={plan.design.edCurrentA} min={0} max={100} unit="A" change={v=>changeDesign({edCurrentA:v})}/></div><button className="ops-secondary" onClick={()=>{try{update(unpoweredCopy(plan));setNotice('Zero bus power selected. Conductor and hardware masses are unchanged. Run to compare.');}catch(e){setError((e as Error).message);}}}>Set power to zero · keep the hardware</button><p className="ops-note">E0 assumes plasma closure and continuous supply. No eclipse, battery or thermal prediction.</p></>}
        {plan.design.recovery!=='none'&&<label className="ops-select">Assistance policy<select aria-label="Assistance policy" value={plan.assistance} onChange={e=>update({assistance:e.target.value as OpsPlan['assistance']})}><option value="after-return">Wait for the next inbound transfer</option><option value="immediate">Recover whenever unoccupied</option></select></label>}
        <details className="ops-details"><summary>Facility & delivery targets</summary><label className="ops-select">Strength material<select aria-label="Operations material" value={plan.design.material} onChange={e=>changeDesign({material:e.target.value})}>{MATERIALS.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label>
          <div className="ops-two">{([['spanKm','Tether span',80,4000,'km'],['altitudeKm','Initial altitude',400,8000,'km'],['tipSpeedKms','Rotational tip speed',.25,2.5,'km/s'],['areaMm2','Cable section',5,2500,'mm²']] as const).map(([key,label,min,max,unit])=><NumberField key={key} label={label} value={plan.design[key]} min={min} max={max} step={key==='tipSpeedKms'?.05:1} unit={unit} change={v=>changeDesign({[key]:v})}/>)}</div>
          <div className="ops-two"><NumberField label="Outbound release phase" value={plan.outboundPhase} min={70} max={210} unit="°" change={v=>update({outboundPhase:v})}/><NumberField label="Inbound release phase" value={plan.inboundPhase} min={40} max={180} unit="°" change={v=>update({inboundPhase:v})}/><NumberField label="Outbound minimum apogee" value={plan.minOutboundApogeeKm} min={120} max={100000} step={100} unit="km" change={v=>update({minOutboundApogeeKm:v})}/><NumberField label="Inbound maximum apogee" value={plan.maxInboundApogeeKm} min={120} max={100000} step={100} unit="km" change={v=>update({maxInboundApogeeKm:v})}/></div>
          <p className="ops-note">Every counted transfer needs a bound orbit and perigee ≥120 km. Outbound energy must increase; inbound energy must decrease. Destinations still differ between runs.</p>
          {plan.design.material==='custom'&&<div className="ops-two"><NumberField label="Custom density" value={plan.design.density} min={500} max={12000} unit="kg/m³" change={v=>changeDesign({density:v})}/><NumberField label="Custom strength" value={plan.design.ultimateGPa} min={.1} max={100} step={.1} unit="GPa" change={v=>changeDesign({ultimateGPa:v})}/></div>}
          {plan.design.recovery==='electrodynamic'&&<div className="ops-two">{([['edLengthKm','Conductor per arm',1,500,'km'],['edAreaMm2','Conductor area',1,200,'mm²'],['edVoltageKv','Drive voltage',0,200,'kV'],['edHardwareT','Electrical hardware',.1,500,'t']] as const).map(([key,label,min,max,unit])=><NumberField key={key} label={label} value={plan.design[key]} min={min} max={max} step={.1} unit={unit} change={v=>changeDesign({[key]:v})}/>)}</div>}
        </details>
        <details className="ops-details"><summary>Generate a finite manifest</summary><div className="ops-two"><NumberField label="Outbound count" value={out} min={1} max={10} change={setOut}/><NumberField label="Inbound count" value={incoming} min={0} max={10} change={setIncoming}/><NumberField label="Generated shipment mass" value={mass} min={.1} max={250} step={.1} unit="t" change={setMass}/><NumberField label="Outbound interval" value={interval} min={20} max={120} unit="min" change={setInterval}/></div><button disabled={![out,incoming].every(Number.isInteger)||out<1||out>10||incoming<0||incoming>10||!Number.isFinite(mass)||mass<.1||mass>250||!Number.isFinite(interval)||interval<20||interval>120} onClick={()=>update({manifest:makeManifest(out,incoming,mass,interval)})}>Replace manifest with these rows</button><p className="ops-note">Explicit replacement only. Later simulation never replenishes this inventory.</p></details>
        <div className="ops-manifest-editor"><h3>Shipment manifest <small>{plan.manifest.length} entries</small></h3><table><caption>{plan.mode==='capacity'?'Queue order · capture times decided by the model':'Fixed capture windows · center ± half-width'}</caption><thead><tr><th>ID</th><th>Mass · t</th><th>Center · min</th></tr></thead><tbody>{plan.manifest.map((r,i)=><tr key={r.id}><th className={r.direction}>{r.id}<small>{r.direction}</small></th><td><input aria-label={`${r.id} mass`} type="number" min={.1} max={250} step={.1} value={Number.isFinite(r.massT)?r.massT:''} onChange={e=>update({manifest:plan.manifest.map((s,j)=>j===i?{...s,massT:e.currentTarget.value===''?NaN:Number(e.currentTarget.value)}:s)})}/></td><td><input aria-label={`${r.id} window center`} type="number" min={0} max={1440} disabled={plan.mode==='capacity'} value={Number.isFinite(r.atMinutes)?r.atMinutes:''} onChange={e=>update({manifest:plan.manifest.map((s,j)=>j===i?{...s,atMinutes:e.currentTarget.value===''?NaN:Number(e.currentTarget.value)}:s)})}/></td></tr>)}</tbody></table></div>
        <div className="ops-run-box">{validation.error&&<p role="alert">{validation.error}</p>}<button className="ops-primary" disabled={busy||!validation.plan} onClick={()=>run(plan)}>{busy?'Calculating shift…':dirty?'Run edited manifest':'Run operations'} ↗</button>
          <div className="ops-file-actions"><button disabled={!validation.plan} onClick={()=>exportData(validateOps(plan),'skyhook-operations-plan.json')}>Export plan</button><button onClick={()=>file.current?.click()}>Import plan</button><input hidden ref={file} type="file" accept=".json,application/json" onChange={async e=>{const selected=e.currentTarget.files?.[0];try{if(selected){if(selected.size>32000)throw Error('Plan exceeds 32 KB.');adopt(readOps(await selected.text()));}}catch(e){setError((e as Error).message);}finally{if(file.current)file.current.value='';}}}/></div>
        </div>
      </aside>
      <section className="ops-flight" aria-label="Operations flight">
        <div className="ops-flight-top"><div><span className="micro">{result?.plan.mode==='schedule'?'FIXED WINDOWS':'CAPACITY EXPERIMENT'}</span><h2>A shift, not a single throw.</h2></div><div><button aria-pressed={!plane} onClick={()=>setPlane(false)}>Globe</button><button aria-pressed={plane} onClick={()=>setPlane(true)}>Orbit plane</button><button aria-pressed={follow} onClick={()=>setFollow(v=>!v)}>Follow</button></div></div>
        {result&&frame?<OperationsScene result={result} time={time} selected={selected} plane={plane} follow={follow} onFallback={fallback}/>:<div className="ops-loading">{busy?'Integrating the manifest…':'Choose a manifest to begin.'}</div>}
        <p className="ops-scene-caption">{dirty?'Unrun edits: this scene still shows the last calculated shift.':'Amber circles: outbound · Violet diamonds: inbound · Cyan: facility'} <span>Markers and cable width enlarged</span></p>
        <label className="ops-track">Track an object<select aria-label="Tracked operations object" value={selected} onChange={e=>setSelected(e.target.value)}><option value="facility">Facility</option>{result?.rows.map(r=><option value={r.id} key={r.id}>{r.id} · {r.direction}</option>)}</select><span>{frame?`${frame.outbound} outbound / ${frame.inbound} inbound at this time`:''}</span></label>
        <div className="ops-transport"><button aria-label={playing?'Pause operations replay':'Play operations replay'} disabled={!result||busy||dirty} onClick={()=>{if(time>=end){clock.current=0;setTime(0);}setPlaying(v=>!v);}}>{playing?'Ⅱ':'▶'}</button><button disabled={!result} onClick={()=>seek(0)}>Restart</button><b>T+ {elapsed(time)}</b><select aria-label="Operations playback speed" value={speed} onChange={e=>setSpeed(Number(e.target.value))}><option value={10}>10× · encounter</option><option value={600}>600×</option><option value={1800}>1,800× · shift</option></select></div>
        <input aria-label="Operations replay time" type="range" min={0} max={end||1} step={1} value={time} disabled={!result} onChange={e=>seek(Number(e.target.value))}/>
        <div className="ops-event-log" role="status"><span className="micro">DISPATCH LOG</span><h3>{lastEvent?.title??'One manifest. No free refills.'}</h3><p>{lastEvent?.detail??'Both service modes still use constructed ideal rendezvous, not independently launched traffic.'}</p></div>
        {result&&<div className="ops-event-list" aria-label="Operations events">{result.events.filter(e=>['capture','release','miss','fuel','limit'].includes(e.kind)).map((e,i)=><button key={i} onClick={()=>{seek(e.t);if(e.shipmentId)setSelected(e.shipmentId);}}><span>{elapsed(e.t)}</span>{e.title}</button>)}</div>}
        <div className="ops-boundary"><b>What is fixed—and what is constructed?</b><p>The finite queue, masses and scheduled windows are supplied before the run. Each approach orbit is then constructed to meet a forecast tip state and independently checked. This is not a solved launch schedule or autonomous guidance system.</p><a href="/lab/operations/method/">Read the operations model →</a></div>
      </section>
      <section className="ops-results" aria-label="Full operations results">
        <div className="ops-results-heading"><div><p className="micro">COMPLETE CALCULATED SHIFT / NOT REPLAY COUNTS</p><h2>What did the next flight cost?</h2></div>{result&&<div><button onClick={()=>{setBaseline(result);setNotice('Pinned this complete shift for comparison.');}}>Pin shift</button><button onClick={()=>exportData({format:'skyhook-operations-report',version:1,...result,frames:undefined,finalFrame:result.frames.at(-1),limitations:'Finite OPS rigid-body experiment. Windows fixed; orbits constructed. No launch, guidance, atmosphere, cable elasticity, debris or endless sustainability claim.'},'skyhook-operations-report.json')}>Export shift report</button></div>}</div>
        {result&&final&&counts?<><div className="ops-receipt"><div><span>Outbound delivered</span><strong>{result.outbound}<small> / {counts.out}</small></strong></div><div><span>Inbound returned</span><strong>{result.inbound}<small> / {counts.in}</small></strong></div><div><span>Missed / unserved</span><strong>{result.missed}<small> / {result.unserved}</small></strong></div><div><span>Propellant spent</span><strong>{f(result.fuelUsedKg/1000,2)}<small> t</small></strong></div><div><span>Electrical input</span><strong>{f(result.busEnergyJ/3.6e9,3)}<small> MWh</small></strong></div></div>
          <p className="ops-outcome">{result.stop==='limit'?'Model limit reached.':`${f(final.t/3600,2)} simulated hours observed.`} {result.reason} {result.rows.filter(r=>r.status==='invalid-release').length} releases outside their destination targets.</p>
          <div className="ops-history-grid"><History r={result} time={time} metric="energy"/><History r={result} time={time} metric="angular"/></div>
          <div className="ops-balance"><section><span className="micro">FINITE TRANSFERS</span><h3>Equal tonnes are not equal recovery.</h3><dl><div><dt>Net energy given to cargo</dt><dd>{plus(gain/1e9)} GJ</dd></div><div><dt>Dry facility energy change</dt><dd>{plus((final.dryEnergyJ-result.initialDryEnergyJ)/1e9)} GJ</dd></div><div><dt>Dry facility angular-momentum change</dt><dd>{plus((final.dryAngular-result.initialDryAngular)/1e12,4)} ×10¹² kg·m²/s</dd></div></dl><p>Negative cargo energy gain gives energy back to the facility during the transfer. It does not automatically restore the original orbit or spin. Failed destination criteria never erase a physical exchange.</p></section><section><span className="micro">NUMERICAL BOOKKEEPING</span><h3>No invisible reset.</h3><dl><div><dt>Actuator mechanical work</dt><dd>{plus(result.actuatorWorkJ/1e9)} GJ</dd></div><div><dt>Energy balance residual</dt><dd>{f(result.energyResidualJ,3)} J</dd></div><div><dt>Angular balance residual</dt><dd>{f(result.angularResidual,2)} kg·m²/s</dd></div></dl><p>The ledger includes entering and leaving cargo, actuator work and signed energy/angular momentum of removed hub propellant. Small numerical residuals test accounting—not real-world safety.</p></section></div>
          <div className="ops-table-wrap"><table className="ops-results-table"><caption>Every shipment remains in the record · tap its ID to inspect the encounter</caption><thead><tr><th>Shipment</th><th>Status</th><th>Original window</th><th>Capture / release</th><th>Payload ΔE</th><th>Payload ΔH <small>10¹² kg·m²/s</small></th><th>Released orbit</th></tr></thead><tbody>{result.rows.map(r=><tr key={r.id}><th><button onClick={()=>{setSelected(r.id);seek(r.encounter?.start??0);setPanel('flight');}}>{r.id} ↗</button><small>{r.massT} t · {r.direction}</small></th><td>{r.status}<small>{r.reason}</small></td><td>{result.plan.mode==='schedule'?`${r.atMinutes} ± ${result.plan.windowMinutes} min`:'Capacity queue'}</td><td>{r.capturedState&&r.encounter?elapsed(r.encounter.capture):'—'} / {r.releasedAt!==undefined?elapsed(r.releasedAt):'—'}{r.encounter&&!r.capturedState&&<small>Forecast: {elapsed(r.encounter.capture)} · not captured</small>}</td><td>{r.energyGainJ!==undefined?`${plus(r.energyGainJ/1e9)} GJ`:'—'}</td><td>{r.angularGain!==undefined?`${plus(r.angularGain/1e12,4)} ×10¹²`:'—'}</td><td>{r.perigeeKm!==undefined?`${f(r.perigeeKm,0)} km / ${r.apogeeKm===null?'escape':f(r.apogeeKm!,0)+' km'}`:'—'}</td></tr>)}</tbody></table></div>
          {baseline&&<div className="ops-comparison"><h3>Against the pinned shift</h3><p>Compare destination requirements, horizon and incoming supply before comparing resource costs. Different deliveries are not interchangeable.</p><table><thead><tr><th>Metric</th><th>Pinned</th><th>Current</th></tr></thead><tbody><tr><th>Outbound / inbound</th><td>{baseline.outbound} / {baseline.inbound}</td><td>{result.outbound} / {result.inbound}</td></tr><tr><th>Mass sent outbound</th><td>{f(baseline.rows.filter(r=>r.status==='delivered').reduce((s,r)=>s+r.massT,0))} t</td><td>{f(result.rows.filter(r=>r.status==='delivered').reduce((s,r)=>s+r.massT,0))} t</td></tr><tr><th>Loaded propellant</th><td>{baseline.plan.design.fuelT} t</td><td>{result.plan.design.fuelT} t</td></tr><tr><th>Spent propellant</th><td>{f(baseline.fuelUsedKg/1000,2)} t</td><td>{f(result.fuelUsedKg/1000,2)} t</td></tr><tr><th>Bus input</th><td>{f(baseline.busEnergyJ/3.6e9,3)} MWh</td><td>{f(result.busEnergyJ/3.6e9,3)} MWh</td></tr><tr><th>Dry hardware mass</th><td>{f(baseline.dryMassKg/1000,2)} t</td><td>{f(result.dryMassKg/1000,2)} t</td></tr></tbody></table><button onClick={()=>{worker.current?.terminate();sequence.current++;setBusy(false);setSelected('facility');setPlan(copy(baseline.plan));if(baseline.plan.design.recovery==='chemical')fuelMemory.current=baseline.plan.design.fuelT;setResult(baseline);seek(0);setNotice('Restored the exact pinned plan and calculated shift.');}}>Restore pinned shift</button></div>}
        </>:<p>Run a manifest to inspect its transfer and resource history.</p>}
      </section>
    </div>
    <footer className="ops-footer"><span>{OPS_MODEL} · rigid-body educational experiment</span><a href="/lab/">Back to Flight Studio ↗</a><a href="/lab/operations/method/">Assumptions & equations ↗</a></footer>
  </main>;
}
